### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by ismangil**
Setting up code scanning provided by GitHub

### CODE REVIEW

**Comment by ismangil** [comment]
GitHub is offering [code scanning](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) for security.

**Comment by sauwming** [comment]
The Csharp analysis failed, but perhaps we can remove it. We only have one C# sample code in our library.
For Java though, not sure why it failed.

**Comment by ismangil** [comment]
> 
> 
> The Csharp analysis failed, but perhaps we can remove it. We only have one C# sample code in our library.

Disabled.

> For Java though, not sure why it failed.

It needs a build command, it can't figure out the autobuild. Disabled for now.

**Review by sauwming — APPROVED** [review]

**Comment by nanangizz** [comment]
Cannot find the build log, how can we know whether the code is built properly or whether it analyses the correct code. From the log, the cpp build took about 4 minutes, seems about right though.

**Review by nanangizz — APPROVED** [review]

**Pull request merged**
