### PR TITLE
Fixed Android build issues on NDK r23 and r24

### PR DESCRIPTION
**Pull request by sauwming**
As reported in #2964, Android SWIG build failed with undefined reference to `ANativeWindow_fromSurface`. The solution is to link with `-landroid`.

I tested with Android NDK r24b and the original report is for NDK r23.

[Internal]: If you're using an older NDK, please help test to make sure it doesn't break the build.

### CODE REVIEW

**Review by trengginas — DISMISSED** [review]

**Comment by sauwming** [comment]
Just added another commit to fix OpenGL ES 2 detection. Please help retest.

**Comment by sauwming** [comment]
I just tested on my older laptop with NDK r21b and it seems okay.

**Review by trengginas — APPROVED** [review]

**Comment by trengginas** [comment]
> I just tested on my older laptop with NDK r21b and it seems okay.

tested here on r21e and without issue

**Comment by nanangizz** [comment]
tried using NDK r20, built okay.

**Comment by nanangizz** [comment]
Tried using NDK r19, also build okay (`PJMEDIA_HAS_VIDEO` set and swig).

**Review by nanangizz — APPROVED** [review]

**Pull request merged**
