### PR TITLE
Support Python3 for github CI

### PR DESCRIPTION
**Pull request by trengginas**
Github CI no longer support Python2.7 ([ref](https://github.com/actions/setup-python/issues/672)), making some tests failing.
This PR will update the unit tests using Python3, it will no longer work on Python2.

### CODE REVIEW

**Comment by sauwming** [comment]
The CI tests still failed.

**Comment by nanangizz** [comment]
There are a lot of warnings:
`/home/runner/work/pjproject/pjproject/tests/pjsua/run.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp`

This may be useful: https://stackoverflow.com/questions/69884878/replacing-imp-with-importlib-maintaining-old-behavior

**Comment by nanangizz** [comment]
In CI Windows:
- `UnicodeEncodeError: 'charmap' codec can't encode character '\x80' in position 482: character maps to <undefined>`
- Some failures in initiating/running pjsua.

Saw some encoding errors in CI Linux too.

**Review by sauwming — APPROVED** [review]

**Review by nanangizz — APPROVED** [review]
pjsua tests in CI Windows produce about 6x errors (out of 2xx tests), mostly about failure in starting pjsua and `FileNotFoundError: [WinError 2] The system cannot find the file specified`. But as it seems to also happens before this Python version upgrade, I think it is not within the scope of this PR.

**Comment by trengginas** [comment]
> pjsua tests in CI Windows produce about 6x errors (out of 2xx tests), mostly about failure in starting pjsua and `FileNotFoundError: [WinError 2] The system cannot find the file specified`. But as it seems to also happens before this Python version upgrade, I think it is not within the scope of this PR.

The failure related to sipp tests and AMRNB codec use. sipp tests will fail because it needs cygwin to run on windows. AMRNB build fails in windows.

**Pull request merged**
