### PR TITLE
oss-fuzz ideal integration

### PR DESCRIPTION
**Pull request by 0x34d**
Added [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) 

#### Why CIFuzz?
-  If there is any bug in PR it can be caught before the merge.

#### New Targets.
- CRYPTO
- HTTP
- URL
- URI 
- Miner update in JSON,  XML ,STUN

### CODE REVIEW

**Comment by sauwming** [comment]
To avoid merging conflict, I want to inform you that we also have a PR in progress in #3422

**Comment by 0x34d** [comment]
> To avoid merging conflict, I want to inform you that we also have a PR in progress in #3422

Thank you information.
I will fix the conflict in my PR after https://github.com/pjsip/pjproject/pull/3422 merge.

**Comment by 0x34d** [comment]
This PR can be merge after resolving https://github.com/pjsip/pjproject/issues/3432

**Comment by 0x34d** [comment]
Will add `clusterfuzzlite` after  https://github.com/google/oss-fuzz/issues/9909 is resolved

**Comment by sauwming** [comment]
The CIFuzz still fails?

**Comment by 0x34d** [comment]
> The CIFuzz still fails?

yes, for that `oss-fuzz` have to merge https://github.com/google/oss-fuzz/pull/9908

**Comment by 0x34d** [comment]
Trigger CI

**Comment by sauwming** [comment]
For the assertion in `fuzz-wav`, I'm not sure that wav player is a good target for fuzzing, since the wav file is supposed to be created locally and should not contain direct data from remote. Hence, it lacks checking such as if the wav contains valid clock rate, channel count, etc.

**Comment by sauwming** [comment]
While for `fuzz-crypto`, it fails the memory sanitiser. It seems that `MD5()` doesn't always fill the entire output (I can't find any info about this in the official doc though, which only says:
`
MD2(), MD4(), and MD5() compute the MD2, MD4, and MD5 message digest of the n bytes at d and place it in md (which must have space for MD2_DIGEST_LENGTH == MD4_DIGEST_LENGTH == MD5_DIGEST_LENGTH == 16 bytes of output)
`
).

```
==78==WARNING: MemorySanitizer: use-of-uninitialized-value
[4363](https://github.com/pjsip/pjproject/actions/runs/4425902981/jobs/7761529848#step:5:4364)
    #0 0x4e62f0 in __interceptor_memcmp /src/llvm-project/compiler-rt/lib/msan/../sanitizer_common/sanitizer_common_interceptors.inc:892:10
[4364](https://github.com/pjsip/pjproject/actions/runs/4425902981/jobs/7761529848#step:5:4365)
    #1 0x534e8d in md5_differential /src/pjsip/tests/fuzz/fuzz-crypto.c:116:18

4376
  Uninitialized value was created by an allocation of 'ssl_md5_hash' in the stack frame of function 'md5_differential'
[4377](https://github.com/pjsip/pjproject/actions/runs/4425902981/jobs/7761529848#step:5:4378)
    #0 0x534cb0 in md5_differential /src/pjsip/tests/fuzz/fuzz-crypto.c:101
```

A simple fix would be: `pj_bzero(ssl_md5_hash, sizeof(ssl_md5_hash)`. But the problem would be, if it doesn't fill the entire output, then of course the `memcmp` result will be different?

**Comment by 0x34d** [comment]
There is other bug in Crypto-Fuzz
i'm working on it.
```
Uninitialized bytes in __interceptor_fopen64 at offset 0 inside [0x702000000180, 25)
==26110==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7ff025cdceb6 in BIO_new_file (/lib64/libcrypto.so.3+0xdceb6) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #1 0x7ff025d1353c  (/lib64/libcrypto.so.3+0x11353c) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #2 0x7ff025d14591 in CONF_modules_load_file_ex (/lib64/libcrypto.so.3+0x114591) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #3 0x7ff025db635f  (/lib64/libcrypto.so.3+0x1b635f) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #4 0x7ff025ab3086 in __pthread_once_slow (/lib64/libc.so.6+0x90086) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #5 0x7ff025dbb87c in CRYPTO_THREAD_run_once (/lib64/libcrypto.so.3+0x1bb87c) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #6 0x7ff025db6c2d in OPENSSL_init_crypto (/lib64/libcrypto.so.3+0x1b6c2d) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #7 0x7ff025dc21db  (/lib64/libcrypto.so.3+0x1c21db) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #8 0x7ff025e87cd8  (/lib64/libcrypto.so.3+0x287cd8) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #9 0x7ff025e883ae  (/lib64/libcrypto.so.3+0x2883ae) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #10 0x7ff025d76211 in EVP_MD_fetch (/lib64/libcrypto.so.3+0x176211) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #11 0x7ff025d794b7 in EVP_Q_digest (/lib64/libcrypto.so.3+0x1794b7) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #12 0x7ff025dfd6f4 in SHA1 (/lib64/libcrypto.so.3+0x1fd6f4) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)
    #13 0x4fea2c in sha1_differential /home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto.c:135:5
    #14 0x4feea3 in LLVMFuzzerTestOneInput /home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto.c:171:5
    #15 0x44c3f1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x44c3f1) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)
    #16 0x44cd40 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x44cd40) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)
    #17 0x44dd90 in fuzzer::Fuzzer::MutateAndTestOne() (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x44dd90) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)
    #18 0x44f797 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x44f797) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)
    #19 0x433d4c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x433d4c) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)
    #20 0x4239e6 in main (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x4239e6) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)
    #21 0x7ff025a4a50f in __libc_start_call_main (/lib64/libc.so.6+0x2750f) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #22 0x7ff025a4a5c8 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x275c8) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #23 0x423a34 in _start (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x423a34) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)

  Uninitialized value was created by a heap allocation
    #0 0x4f822d in malloc (/home/oblivion/project/pjproject/tests/fuzz/fuzz-crypto+0x4f822d) (BuildId: dfedddef2fe9aaf3dbac4f08535c47d44b1e7686)
    #1 0x7ff025d144ef in CONF_get1_default_config_file (/lib64/libcrypto.so.3+0x1144ef) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/lib64/libcrypto.so.3+0xdceb6) (BuildId: 5f86a956fe1375ca4bcc060da69449c1840d3ddd) in BIO_new_file
```

**Comment by 0x34d** [comment]
Now you can call for merge.

**Review by sauwming — APPROVED** [review]

**Review by nanangizz — APPROVED** [review]

**Pull request merged**
