### PR TITLE
Avoid crash when info->jb_max equals frame ptime 

### PR DESCRIPTION
**Pull request by SebaLedesma**
See issue #3271

### CODE REVIEW

**Comment by silentindark** [comment]
@SebaLedesma 
I think that should be one commit - 
"Avoid crash when info->jb_max equals frame ptime" the last one?

**Comment by nanangizz** [comment]
Yes, we will do squash & merge, so only the last diff matters and it looks clean.

Few notes though:
- video stream may need to be updated too?
- perhaps need to fix/update the pjsua option `--jb-max-size` help string too (from `in frames` to `in msec`):
  https://github.com/pjsip/pjproject/blob/74569f926a2f553006d4bbac70c7371dfb1eb400/pjsip-apps/src/pjsua/pjsua_app_config.c#L170
  This may sound like a backward compatibility issue, but then the underlying code is already buggy (the setting won't work as expected), so I guess it is okay to change it. Moreover, frame time may vary a lot, e.g: for audio it can be ranging from 1ms to 30 ms (depends on the codec), while for video, the range is even broader (depends on frame rate), so I guess it is not very sensible to have JB max size setting in frame count.

**Comment by SebaLedesma** [comment]
Sorry about the late, we are heading an exhibition so everyone is running here :)
1 - The logic is generic for audio/video stream, so the solution is valid for both. Say that, I have more experience with audio, and we are doing some testing/optimizations for opus encoding, when they are more polished I will create their respective PR.
2 - You are right, the command line help also needs to be updated.  I'll put on my agenda.

**Comment by sauwming** [comment]
I can help fix this if you'd like. But since you're using master branch in your repo, I would like to ask your permission first if it's okay if I commit directly (I received a warning message just now when trying to resolve the code conflict).

**Comment by sauwming** [comment]
I created a new PR #3551 to resume this.

**Pull request closed without merging**
