### PR TITLE
Add Oboe audio device backend for Android

### PR DESCRIPTION
**Pull request by nanangizz**
To find out about Oboe, please check here: https://github.com/google/oboe.

### How to enable Oboe in PJSIP Project
1. Download Oboe prefab package (`.aar` file) from [Google Maven](https://maven.google.com/web/index.html?q=oboe#com.google.oboe:oboe) or [Oboe GitHub repository](https://github.com/google/oboe/releases/). Tested version is 1.5.0.
2. Extract it somewhere, e.g: `/SOME_PATH/oboe-1.5.0`
3. Run configure script with Oboe prefix path specified, e.g:
    ```
    ./configure-android --with-oboe=/SOME_PATH/oboe-1.5.0
    ```
   Check the configure output, make sure Oboe is detected:
    ```
    Using Oboe prefix... /SOME_PATH/oboe-1.5.0
    checking Oboe usability... yes
    Checking sound device backend... Oboe
    ```
4. Copy `liboboe.so` from `prefab/modules/oboe/libs` to your Android application library directory (such as `jniLibs/armeabi` or `jniLibs/arm64-v8a`), e.g:
    ```
    cp /SOME_PATH/oboe-1.5.0/prefab/modules/oboe/libs/android.arm64-v8a/liboboe.so \
       pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/arm64-v8a \
    ```
5. Build PJSIP and app as usual as described in the [Getting Started wiki page](https://trac.pjsip.org/repos/wiki/Getting-Started/Android).

### Features
1. Audio device enumeration (currently Android JNI and OpenSLES backends do not have this).
2. Handle audio device stream disconnection, for example when headset is plugged/unplugged.

### Limitation
Oboe provides low latency audio stream, however from the tests (on Samsung S10), we can only get low latency mode in playback direction. Perhaps it is because we don't apply sample rate conversion (`setSampleRateConversionQuality()`) for capture direction, however when it is configured, audio data callback is never invoked while no error reported in the Oboe initialization. Also exclusive mode (`setSharingMode(Exclusive)`) is currently disabled as otherwise somehow capture stream won't be able to be reopened after headset is plugged/unplugged.

### CODE REVIEW

**Comment by sauwming** [comment]
I found several issues in their Github such as:
https://github.com/google/oboe/discussions/1228 (With Low Latency performance mode, recording doesn't work in some devices)
https://github.com/google/oboe/discussions/1229 (Low Latency Input on Galaxy Note 20 is silent)
and a few others.

So perhaps we can try the suggestion mentioned there. And in case that you haven't, test with the sample app OboeTester as well, and if it's reproducible there, we can report our findings and join the discussion in their issue page.

**Comment by nanangizz** [comment]
> I found several issues in their Github such as:
> [google/oboe#1228](https://github.com/google/oboe/discussions/1228) (With Low Latency performance mode, recording doesn't work in some devices)
> [google/oboe#1229](https://github.com/google/oboe/issues/1229) (Low Latency Input on Galaxy Note 20 is silent)
> and a few others.
> 
> So perhaps we can try the suggestion mentioned there. And in case that you haven't, test with the sample app OboeTester as well, and if it's reproducible there, we can report our findings and join the discussion in their issue page.

For now, still not sure if we should handle the issue, because we don't know which devices are affected (and how to check it) and the proposed solution involves private/internal API. Without low latency enabled in the recording dir, the overall latency in a call sounds just fine to me actually.

**Comment by sauwming** [comment]
If the inability to open low-latency recording (in some devices) is Oboe's limitation, then I believe that's fine. But what if it's because there is something missing in our wrapper? So that's why I suggest to ask for confirmation if it's indeed the case, or perhaps we should test on a device that's known to work?

**Comment by nanangizz** [comment]
Right, haven't tested with OboeTester app yet. Also, there is 1.6.0 with some Samsung fixes, so I will try it first, if the issue is still there, will try OboeTester.

Btw, I think we need to test this Oboe with more Android devices @sauwming @trengginas.

**Comment by nanangizz** [comment]
The issue seems to persist with 1.6.0 and it is reproducible with OboeTester app. Also created an issue report https://github.com/google/oboe/issues/1320.

**Review by trengginas — APPROVED** [review]

**Comment by TechGuyVN** [comment]
I Have follow your suggestion above:
- Download  aar & source inbot oboe 1.7.0
- run script build_all_android.sh with success lib generate in build folder
- run script: ./configure-android --with-oboe=/SOME_PATH/oboe-1.7.0
- this script always return : 
`
Using Oboe prefix... /SOME_PATH/oboe-1.7.0
checking Oboe usability... no
Checking sound device backend... Android
`
- i have use config for pjsip build with: --with-oboe=/home/pjsip-android-builder-master/oboe-1.7.0
- i see in log build have this error too:
image

Can you help me solve this

**Comment by TechGuyVN** [comment]
Im try to integrate build success but when i make call:
- Make outbound call can hear voice
- Receive inbound call, can not hear sound view log i see this error:
`
Error while connecting audio media to sound device
    java.lang.Exception: Title:       pjsua_conf_connect(id, sink.id)
    Code:        420002
    Description: Unknown error from audio driver (PJMEDIA_EAUD_SYSERR)
    Location:    ../src/pjsua2/media.cpp:219
    
        at org.pjsip.pjsua2.pjsua2JNI.AudioMedia_startTransmit(Native Method)
        at org.pjsip.pjsua2.AudioMedia.startTransmit(:52)
        at net.gotev.sipservice.SipCall.handleAudioMedia(:492)
        at net.gotev.sipservice.SipCall.onCallMediaState(:241)
        at org.pjsip.pjsua2.pjsua2JNI.SwigDirector_Call_onCallMediaState(:2758)
        at org.pjsip.pjsua2.pjsua2JNI.Call_answer(Native Method)
        at org.pjsip.pjsua2.Call.answer(:124)
        at net.gotev.sipservice.SipCall.acceptIncomingCall(:310)
        at net.gotev.sipservice.SipService.handleAcceptIncomingCall(:286)
        at net.gotev.sipservice.SipService.lambda$onStartCommand$1(:130)
        at net.gotev.sipservice.SipService.a(Unknown Source:0)
        at net.gotev.sipservice.d.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

I try to enable device like that with no success:
`
      SipEndpoint.instance().audDevManager().setCaptureDev(pjsua_snd_dev_id.PJSUA_SND_DEFAULT_CAPTURE_DEV);
      SipEndpoint.instance().audDevManager().setPlaybackDev(pjsua_snd_dev_id.PJSUA_SND_DEFAULT_CAPTURE_DEV);

`

can you help me this case

**Pull request merged**
