### PR TITLE
Add support for embedded headers received in Contact header of SIP 3xx

### PR DESCRIPTION
**Pull request by di-shi**
Insert SIP 3xx Contact header URI header parameters (embedded headers) into redirected SIP INVITE message, then remove the header parameters from the URI to prevent the embedded headers from being inserted twice.

### CODE REVIEW

**Comment by di-shi** [comment]
For https://github.com/pjsip/pjproject/issues/3084

**Comment by bennylp** [comment]
Thank you for looking into this topic. I think if we are to implement this, we'd better follow the guidelines in RFC 3261 section 8.1.3.4 and 19.1.5 regarding forming headers from URI.

**Comment by fenichelar** [comment]
@bennylp I believe this is already compliant with RFC 3261. Can you please elaborate on what specifically needs to be changed?

**Comment by bennylp** [comment]
Since the URI containing the headers is taken from the 3xx response from the server, it's possible that a rouge or malfunctioning server sends invalid headers such as From, Via, Call-ID, Contact, etc., thus we need to follow the details from the sections that I mentioned.

**Pull request closed without merging**
