### PR TITLE
Do not preserve ownership when installing libs

### PR DESCRIPTION
**Pull request by martin-flaska**
This is fixing 'host-user-contaminated' Yocto QA warning:

https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#ref-tasks-install

### CODE REVIEW

**Comment by sauwming** [comment]
Unfortunately I think the option is not available on all platforms.
When I tried it here on Mac, it gave the error `illegal option`.

**Comment by martin-flaska** [comment]
@sauwming I replaced `cp` with recommended [install](https://www.gnu.org/software/coreutils/manual/html_node/install-invocation.html#install-invocation) command for installation process. is this command also available on Mac?

**Comment by sauwming** [comment]
Yes, it's available on Mac. From a quick check, it also seems to be available on most platforms that I check. The problem is I'm not 100% sure to be the first to approve this. Will need to wait for the other's vote of confidence or if there's any objection.

**Comment by martin-flaska** [comment]
Thank you @sauwming for your answer. No problem if it is posponed. I noticed more QA warnings related to the Yocto build. Some of them are already fixed since 2.11.1 version was released. I have just some quick workaround solutions for now, if I find some good solution later, I will share.

**Comment by nanangizz** [comment]
Looks okay to me (not Makefile expert).

Btw, will it be better to make it a bit more configurable, e.g: add `AC_CHECK_TOOL(INSTALL, ..)` in the `aconfigure.ac` and `cc-*.mak.in`, so user can add custom options or even use an alternative install tool?

**Comment by martin-flaska** [comment]
I found some issues with installing sym links which I need to solve. Closing...

**Pull request closed without merging**
