### PR TITLE
Add support to boringssl

### PR DESCRIPTION
**Pull request by trengginas**
This ticket will add support to boringssl.

BoringSSL is a fork of OpenSSL that is designed to meet Google's needs.
Since it is a fork to OpenSSL, you can use `--with-ssl` option to `configure` command.

You can get the latest boringssl from https://github.com/google/boringssl.
This patch is tested to build correctly on [r68addd](https://github.com/google/boringssl/commit/68addd)

### CODE REVIEW

**Review by nanangizz — APPROVED** [review]

**Comment by sauwming** [comment]
There seem to be some conflicts with the master.

Also add in the description about the boringssl version and repo (I believe this is for Android repo right? while for the main repo it seems to build fine without any patch). And make sure that this has been tested to build fine with the main repo as well.

**Comment by trengginas** [comment]
> There seem to be some conflicts with the master.
> 
> Also add in the description about the boringssl version and repo (I believe this is for Android repo right? while for the main repo it seems to build fine without any patch). And make sure that this has been tested to build fine with the main repo as well.

The original report was related to build issue specific to Android. However I tested using MacOS and it also failed to build although the configure script detected the OpenSSL support. With this patch, the build is successful on MacOS.

**Comment by trengginas** [comment]
> There seem to be some conflicts with the master.
> 
> Also add in the description about the boringssl version and repo (I believe this is for Android repo right? while for the main repo it seems to build fine without any patch). And make sure that this has been tested to build fine with the main repo as well.

The original report was related to build issue specific to Android. However I tested using MacOS and it also failed to build although the configure script detected the OpenSSL support. With this patch, the build is successful on MacOS.

**Review by sauwming — APPROVED** [review]
There are a couple of recent changes in OpenSSL (verify_cb() and session reuse PRs), so if building BoringSSL produces no error with those changes, please merge this.

**Pull request merged**
