### PR TITLE
Fix audio & video conference bridge: adding port may not update port counter

### PR DESCRIPTION
**Pull request by nanangizz**
This is to fix https://github.com/pjsip/pjproject/pull/3928#issuecomment-2484827371.

After investigation, it is caused by invalid port counter (e.g: zero or `-1` while there are actually some ports added). Conference bridge uses the port counter to iterates the ports, so when it is invalid, no media flow will happen. Furthermore, such invalid port counter case may happen when a port is removed before the add port operation, including increasing the port counter, is completed. The add port operation can never be completed when no async operation is queued.

This PR fix it by:
- introducing a new async operation for add port operation,
- only decrement port counter when port add is completed (i.e: internal port state `is_new` is false).

### CODE REVIEW

**Review by sauwming — DISMISSED** [review]

**Comment by sauwming** [comment]
pjsua-test failed, and it seems genuine, already rerun it twice.

**Comment by nanangizz** [comment]
Just tried the failing Python test using this branch on MacOS (13.2/Intel), still not reproducible.

**Comment by sauwming** [comment]
Yes, that's strange, I also tried both tests here on my Mac and they completed successfully.

But it's most certainly because of this PR since this is the only one that failed the CI tests in https://github.com/pjsip/pjproject/actions. I have also repeated the CI tests many times over the night and the failed results are consistent.

**Comment by sauwming** [comment]
Your intuition is correct. The '%' causes the issue.
Passing the URI as format specifier doesn't make sense: 
`snprintf(.., ..., "sip:I%20have%20spaces@example.net", ...)`

Although not sure why only in this PR it raises the error.

Perhaps we should change it to `strstr(.., "%p)`?

Another potential issue is that `pjmedia_conf_add_port()` never specifies that `port_name` must be NULL terminated, so we probably shouldn't call `pj_pool_create(..., name->ptr)`

**Comment by nanangizz** [comment]
> Perhaps we should change it to `strstr(.., "%p")`?

Agree. But it may still have a problem, when the name accidentally has `%p`, the pool name will not be as expected. Perhaps we should also escape/replace any unintended `%`, but this needs to be done in the apps.

> Another potential issue is that `pjmedia_conf_add_port()` never specifies that `port_name` must be NULL terminated, so we probably shouldn't call `pj_pool_create(..., name->ptr)`

Agree.

**Review by sauwming — APPROVED** [review]

**Review by trengginas — APPROVED** [review]

**Pull request merged**
