### PR TITLE
Fix parallel build failure

### PR DESCRIPTION
**Pull request by sauwming**
There are a couple of issues reported in #2300 so far:
- Failure in building pjsua2 because pjsua build hasn't been completed. This is reported by edacval  [here](https://github.com/pjsip/pjproject/issues/2300#issuecomment-591274496)). After investigation, this turns out to be caused by a typo in pjsip's Makefile which causes incorrect dependency.
- Failure in building swig component as described by edacval [here](https://github.com/pjsip/pjproject/issues/2300#issuecomment-591845431). This is because the working directory is included in `pj_target_name`.

### CODE REVIEW

**Comment by nanangizz** [comment]
the reported problem seems to be on simple 'make', while parallel build 'make -jN' is just fine?
as long as the problem is reproducible and fixed by this patch, it is okay.

**Comment by sauwming** [comment]
This fix is not for the original report, but for the other one reported by edacval.
```
gcc -o ../lib/libpjsua2.so.2 \
     output/pjsua2-lib-x86_64-unknown-linux-gnu/account.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/endpoint.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/json.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/persistent.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/types.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/siptypes.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/call.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/presence.o  output/pjsua2-lib-x86_64-unknown-linux-gnu/media.o -lpjsua -lpjsip-ua -lpjsip-simple -lpjsip -lpjmedia-audiodev -lpjmedia-videodev -lpjmedia-codec -lpjmedia -lpjnath -lpjlib-util -lpj -lresample -lilbccodec -lg7221codec -lyuv -lwebrtc -lsrtp2 -lgsm -lspeex -lspeexdsp -lportaudio  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -lopus -lssl -lcrypto -lvpx -luuid -lm -lrt -lpthread  -L/usr/lib -pthread -lSDL2  -lavdevice -lavformat -lavcodec -lswscale -lavutil  -lv4l2   -L/tmp/makepkg/pjproject/src/pjproject-2.10/pjlib/lib -L/tmp/makepkg/pjproject/src/pjproject-2.10/pjlib-util/lib -L/tmp/makepkg/pjproject/src/pjproject-2.10/pjnath/lib -L/tmp/makepkg/pjproject/src/pjproject-2.10/pjmedia/lib -L/tmp/makepkg/pjproject/src/pjproject-2.10/pjsip/lib -L/tmp/makepkg/pjproject/src/pjproject-2.10/third_party/lib -L/usr/lib -pthread -lSDL2 -lavdevice -lavformat -lavcodec -lswscale -lavutil  -lv4l2  -lvpx -L/usr/lib -pthread -lSDL2 -lavdevice -lavformat -lavcodec -lswscale -lavutil  -lv4l2  -lvpx -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  -lstdc++ -shared -Wl,-soname,libpjsua2.so.2
/usr/bin/ld: cannot find -lpjsua
collect2: error: ld returned 1 exit status
```
Unable to reproduce it locally despite several tries, although I suppose it's due to the nature of the parallelism. Nevertheless, the error seems very obvious.

**Comment by nanangizz** [comment]
ah ok, then the commit message is kind of misleading I think?

**Comment by sauwming** [comment]
Yes, I realised it when creating the PR and that's why I changed it from "re #2300" to "reported in #2300". It seems still not quite clear though, so I just added more info above.

**Comment by sauwming** [comment]
change to what? The title is already correct I think, the problem happens if the build is parallel, unlike the original issue reported in #2300, which is the opposite.

btw, managed to reproduce the issue here by adding some sleep when building pjsua lib, to make sure that it doesn't complete before pjsua2:
```
 $(PJSUA_LIB_LIB) $(PJSUA_LIB_SONAME): $(PJSIP_LIB) $(PJSIP_SONAME) $(PJSIP_SIMPLE_LIB) $(PJSIP_SIMPLE_SONAME) $(PJSIP_UA_LIB) $(PJSIP_UA_SONAME)
+       @sleep 10
        $(MAKE) -f $(RULES_MAK) APP=PJSUA_LIB app=pjsua-lib $(subst /,$(HOST_PSEP),$(LIBDIR)/$@)
```

and can confirm that the patch works.

**Comment by nanangizz** [comment]
i thought the typo is kind of generic, may trouble generic build, not specific to parallel build. ok then.

**Pull request merged**
