### PR TITLE
fix avi play crash

### PR DESCRIPTION
**Pull request by jimying**
as title
ref to issue #2870 
I have test it okay on Mac & Windows

### CODE REVIEW

**Comment by silentindark** [comment]
@sauwming @nanangizz  Could you please review this change?

**Comment by sauwming** [comment]
I cannot play the provided sample avi. If you can convert it to `h264`, it would be great.
If not, can you tell us more about the value of `size_read` when the issue happened and if it is negative, why it could happen?

**Comment by jimying** [comment]
> I cannot play the provided sample avi. If you can convert it to `h264`, it would be great.
> If not, can you tell us more about the value of `size_read` when the issue happened and if it is negative, why it could happen?


sorry  for delay.  please visit http://a.jimying.fun/video/
panda.h264.avi : is h264 format avi
panda1.mp4 is the raw mp4 file

**Comment by jimying** [comment]
> I cannot play the provided sample avi. If you can convert it to `h264`, it would be great. If not, can you tell us more about the value of `size_read` when the issue happened and if it is negative, why it could happen?

when crash, size_read = 0, I modify to debug, log as follow: 
```
20:47:07.915           avi_player.c  ------------> size_read = 0
20:47:07.921                 ffmpeg  mpeg4: header damaged
20:47:07.921    ffmpeg_vid_codecs.c  ffmpeg err -1094995529: Invalid data found when processing input
20:47:07.921              aviplay.c  codec_get_frame() error: Unknown error 220087
20:47:07.961           avi_player.c  File port /Users/jimying/Downloads/panda.avi EOF
20:47:07.962           avi_player.c  File port /Users/jimying/Downloads/panda.avi rewinding..
Segmentation fault: 11
```

**Comment by sauwming** [comment]
When I tried to play `panda.h264.avi` using OpenH264, it would fail much earlier during initialization, which I suppose due to the damaged header(?):
```
11:19:35.221         [OPENH264_LOG]  [L1] [OpenH264] this = 0x0x6000019a71b0, Error:Invalid bitrate settings in total configure, bitrate= 0
11:19:35.221         [OPENH264_LOG]  [L1] [OpenH264] this = 0x0x6000019a71b0, Error:WelsInitEncoderExt(), ParamValidationExt failed return 16.
11:19:35.221         [OPENH264_LOG]  [L1] [OpenH264] this = 0x0x6000019a71b0, Error:CWelsH264SVCEncoder::Initialize(), WelsInitEncoderExt failed.
```

Thanks for the additional info regarding the value of `size_read`. I still don't understand thou, how a value of zero (and not negative as I thought earlier) can lead to a crash. The following code should be fine even when `size_read == 0`:
```
        size_to_read -= size_read;
         pj_bzero((char *)frame->buf + frame->size - size_to_read,
                  size_to_read);
```
So perhaps you can provide us with the stack trace of the crash?

**Comment by jimying** [comment]
@sauwming 
I have no environment for now， I will supply the crash stack later

or 
I build pjsip video support use ffmpeg h264, not openH264.  You can build again use ffmpeg h264, and trace again ^_^

**Comment by sauwming** [comment]
Okay, I could reproduce it here and it is actually our ffmpeg codec wrapper "bug". https://github.com/pjsip/pjproject/blob/master/pjmedia/src/pjmedia-codec/ffmpeg_vid_codecs.c#L1832:
```
    /* ffmpeg warns:
     * - input buffer padding, at least FF_INPUT_BUFFER_PADDING_SIZE
     * - null terminated
     * Normally, encoded buffer is allocated more than needed, so lets just
     * bzero the input buffer end/pad, hope it will be just fine.
     */
#if LIBAVCODEC_VER_AT_LEAST(56,35)
    pj_bzero(avpacket.data+avpacket.size, AV_INPUT_BUFFER_PADDING_SIZE);
```

So when the input frame size is already at the maximum, which is the case of AVI_EOF in `avi_player.c`, the `pj_bzero()` above will cause buffer overwrite. In my test, it will overwrite the vid_port's stream to `NULL` and cause the crash in `pjmedia_vid_dev_stream_put_frame(strm, ...)` since `strm` is `NULL`, exactly as you reported in #2870.

So the fix you proposed is not quite correct, although it does prevent the issue from happening (returning `PJ_EEOF` will prevent the call to `pjmedia_vid_codec_decode()` in `aviplay`:
```
    status = pjmedia_port_get_frame(port_data->src_port, &enc_frame);
    if (status != PJ_SUCCESS) goto on_error;
    
    status = pjmedia_vid_codec_decode(codec, 1, &enc_frame,
                                      (unsigned)frame->size, frame);
```
which of course prevents the problematic ffmpeg decode above from being invoked.

Will update you again when I figure out the proper fix for this.

**Comment by sauwming** [comment]
My proposed fix is in PR #2940.

**Comment by jimying** [comment]
@sauwming  Yes，you find the final reason.  
But i think that if read video file EOF,  pjmedia_port_get_frame should return an error code (PJ_EOF)  and no need continue to decode

**Comment by sauwming** [comment]
We should still try to decode whatever has been read since it's possible the decode can still be successful, for example in the case that the file is slightly corrupted at the end.

What we can do is to skip the decode if the frame is completely empty. I just updated the PR.

**Comment by jimying** [comment]
@sauwming  I have see the pr,  see no problem

**Pull request closed without merging**
